version: '3.2'

services:
    database:
        build: ../../docker_contexts/database
        image: yvideodb
        volumes:
         - ${YVIDEO_SQL_DATA}:/var/lib/mysql
        ports:
        - target: 3306
          published: 3306
          mode: host
        environment:
            MYSQL_USER: dev_user
            MYSQL_PASSWORD: dev
            MYSQL_ROOT_PASSWORD: test

volumes:
    database:

