version: '3.2'

services:
    server:
        build:
            context: ../../docker_contexts/server/dev
            dockerfile: Dockerfile
            args:
                sites_available: ${SITES_FOLDER_NAME}
        image: server
        ports:
        - target: 80
          published: 80
          mode: host
        volumes:
        - ${yvideojs}:/usr/local/apache2/htdocs/yvideojs
        - ${subtitle_timeline_editor}:/usr/local/apache2/htdocs/subtitle-timeline-editor
        - ${TimedText}:/usr/local/apache2/htdocs/TimedText
        - ${EditorWidgets}:/usr/local/apache2/htdocs/EditorWidgets

