version: '3.1'

services:
    server:
        build:
            context: ../../docker_contexts/server/dev
            dockerfile: Dockerfile
            args:
                sites_available: ${SITES_FOLDER_NAME}
        image: server
        ports:
         - "80:80"

