version: '3.2'

services:
    server:
        build:
            context: ../../docker_contexts/server/dev
            dockerfile: Dockerfile
            args:
                sites_available: ${SITES_FOLDER_NAME}
        image: server
        ports:
        - target: 80
          published: 80
          mode: host

