version: '3.2'

services:
    ylex:
        build:
            context: ../../docker_contexts/dev/ylex
            dockerfile: Dockerfile
        image: ylex_dev
        command: ["sbt", "run"]
        ports:
        - target: 9000
          published: 9001
          mode: host
        volumes:
        - ${yvideo_dict_lookup}:/yvideo-dict-lookup
        stdin_open: true

volumes:
    ylex:

