version: '3.2'

services:
    yvideo:
        build:
            context: ../../docker_contexts/dev/yvideo
        image: yvideo_dev
        command: ["sbt", "run"]
        stdin_open: true
        volumes:
        - ${yvideo}:/yvideo
        ports:
        - target: 9000
          published: 9000
          mode: host

volumes:
    yvideo:

