version: '3'

services:
    database:
        build: "../ayamelDBDockerfile/."
        image: yvideodb
        ports:
         - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "test"
            MYSQL_DATABASE: yvideodb
    yvideo:
        depends_on:
         - database
        build: "../AyamelDockerfile/."
        image: yvideo
        volumes:
         - /home/david/Documents/GitHub/Ayamel:/Ayamel
         - /var/www/html:/var/www/html
        stdin_open: true
        environment:
            YVIDEODB: database:3306
                
#        command: ["./runApp.sh"]

volumes:
    yvideo:
