version: '3'

services:
    yvideo:
        volumes:
         - ./Ayamel:/Ayamel
         - ./Ayamel.js:/var/www/html/Ayamel.js
         - ./EditorWidgets:/var/www/html/EditorWidgets
         - ./subtitle-timeline-editor:/var/www/html/subtitle-timeline-editor
         - ./TimedText:/var/www/html/TimedText

        command: ["sbt", "test"]

volumes:
    yvideo:

