version: '3'

services:
    yvideo:
        depends_on:
         - database
         - lamp
        build:
            context: production
            args:
                sbt_version: 0.13.8
        image: yvideo

        command: bash -c "sbt clean stage && target/universal/stage/bin/ayamelexamples"
    lamp:
        build:
            context: production
            dockerfile: Lamp
        image: lamp:production

