version: '2'

services:
    database:
        build: "~/Documents/Docker/ayamelDBDockerfile/."
        image: yvideodb
        ports:
         - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "test"
            MYSQL_DATABASE: yvideodb
    yvideo:
        depends_on:
         - database
        build: "~/Documents/Docker/AyamelDockerfile/."
        image: yvideo
        environment:
            YVIDEODB: database:3306
#        command: bash -c "/Ayamel-Examples/run.sh"
