version: '2'

services:
    database:
        build: "~/Docker/ayamelDBDockerfile/."
        image: yvideodb
        ports:
         - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "test"
            MYSQL_DATABASE: yvideodb
    yvideo:
        depends_on:
         - database
        build: "~/Docker/AyamelDockerfile/."
        image: yvideo
        environment:
            YVIDEODB: database:3306
                
        command: ["./runApp.sh"]
