version: '3'

services:
    yvideo_test:
        depends_on:
         - server
         - database
        build:
            context: test
            args:
                sbt_version: 0.13.8
            dockerfile: Dockerfile
        image: yvideo_test
        command: ["sbt", "test"]

    database:
        build: db
        image: yvideodb
        ports:
         - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "test"

    server:
        build: server
        ports:
         - "80:80"

