version: '3'

services:
    database:
        build: "db/"
        image: yvideodb
        ports:
         - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "test"
            MYSQL_DATABASE: yvideodb
    yvideo:
        depends_on:
         - database
        build: "yvideo/"
        image: yvideo
        environment:
            YVIDEODB: database:3306

