version: '3'

services:
    database:
        build: "../ayamelDBDockerfile/."
        image: yvideodb
        ports:
         - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "test"
            MYSQL_DATABASE: yvideodb
    yvideo:
        depends_on:
         - database
        build: "../AyamelDockerfile/."
        image: yvideo
        volumes:
         - {{Ayamel}}:/Ayamel
         - {{Ayamel.js}}:/var/www/html/Ayamel.js
         - {{EditorWidgets}}:/var/www/html/EditorWidgets
         - {{subtitle-timeline-editor}}:/var/www/html/subtitle-timeline-editor
         - {{TimedText}}:/var/www/html/TimedText
        stdin_open: true
        environment:
            YVIDEODB: database:3306
                
        command: ["./runApp.sh"]

volumes:
    yvideo:
