version: '3'

services:
    yvideo_test:
        depends_on:
         - lamp
         - database
        build:
            context: test/yvideo
            args:
                sbt_version: 0.13.8
            dockerfile: Dockerfile
        image: yvideo_test
        command: ["sbt", "test"]

    ylex_test:
        depends_on:
         - lamp
         - database
        build:
            context: test/ylex
            args:
                sbt_version: 0.13.8
            dockerfile: Dockerfile
        image: yvideo_test
        command: ["sbt", "test"]

    database:
        build: db
        image: yvideodb
        ports:
         - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "test"

    lamp:
        build: lamp
        ports:
         - "80:80"

