version: '3'

services:
    database:
        build: db
        image: yvideodb
        ports:
         - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "test"
        volumes:
         - /var/lib/mysql:

volumes:
    database:

