version: '3'

services:
    yvideo:
        depends_on:
         - database
        build: "yvideo/"
        image: yvideo
        environment:
            YVIDEODB: database:3306

        command: bash -c "sbt clean stage && target/universal/stage/bin/ayamelexamples"

