version: '3'

services:
    yvideo_dev:
        depends_on:
         - database
         - lamp
        build:
            context: dev
            args:
                sbt_version: 0.13.8
            dockerfile: Dockerfile
        image: yvideo_dev
        volumes:
         - ${Ayamel}:/Ayamel
        stdin_open: true
        ports:
         - "9000:9000"
        command: ["sbt", "${dev_command}"]

    lamp:
        image: tutum/lamp:latest
        ports:
         - "80:80"
        volumes:
         - ${Ayamel_js}:/app/Ayamel.js
         - ${subtitle_timeline_editor}:/app/subtitle-timeline-editor
         - ${TimedText}:/app/TimedText
         - ${EditorWidgets}:/app/EditorWidgets


    database:
        volumes:
         - ${YVIDEO_SQL_DATA}:/var/lib/mysql

volumes:
    yvideo:
    lamp:
    database:

