version: '3'

services:
    yvideo:
        depends_on:
         - database
         - lamp
        build: dev
        image: yvideo
        volumes:
         - ${Ayamel}:/Ayamel
        stdin_open: true
        command: ["sbt", "${dev_command}"]

    lamp:
        image: tutum/lamp:latest
        ports:
         - "80:80"
        volumes:
         - ${Ayamel_js}:/app/Ayamel.js
         - ${subtitle_timeline_editor}:/app/subtitle-timeline-editor
         - ${TimedText}:/app/TimedText
         - ${EditorWidgets}:/app/EditorWidgets

volumes:
    yvideo:
    lamp:

