version: '3'

services:
    yvideo_prod:
        depends_on:
         - server
         - database
        build:
            context: production
            args:
                sbt_version: 0.13.8
            dockerfile: Dockerfile
        image: yvideo_prod
        ports:
         - "9001:9001"
        command: bash -c "sbt clean stage && target/universal/stage/bin/ayamelexamples -Dhttp.port=9001 -DapplyEvolutions.default=true"

    database:
        volumes:
         - ${YVIDEO_SQL_DATA}:/var/lib/mysql

    server:
        build: server
        ports:
         - "80:80"
         - "443:443"

volumes:
    database:

