version: '3'

services:
    yvideo_dev:
        depends_on:
         - database
         - server
        build:
            context: dev/yvideo
            args:
                sbt_version: 0.13.8
            dockerfile: Dockerfile
        image: yvideo_dev
        volumes:
         - ${Ayamel}:/Ayamel
        stdin_open: true
        ports:
         - "9000:9000"
        command: ["sbt", "${dev_command}"]

    ylex_dev:
        depends_on:
         - database
         - server
        build:
            context: dev/ylex
            args:
                sbt_version: 0.13.8
            dockerfile: Dockerfile
        image: ylex
        volumes:
            - ${DictionaryLookup}:/DictionaryLookup
        stdin_open: true
        ports:
         - "9005:9000"
        command: ["sbt", "${dev_command}"]

    server:
        build:
            context: server
            dockerfile: Dockerfile
        image: server
        ports:
         - "80:80"
        volumes:
         - ${Ayamel_js}:/usr/local/apache2/htdocs/Ayamel.js
         - ${subtitle_timeline_editor}:/usr/local/apache2/htdocs/subtitle-timeline-editor
         - ${TimedText}:/usr/local/apache2/htdocs/TimedText
         - ${EditorWidgets}:/usr/local/apache2/htdocs/EditorWidgets

    database:
        volumes:
         - ${YVIDEO_SQL_DATA}:/var/lib/mysql

volumes:
    yvideo_dev:
    ylex_dev:
    server:
    database:

