version: '3'

volumes:
    yvideo_dev:
    ylex_dev:
    server:
    database:

services:
    server:
        build:
            context: server
            dockerfile: Dockerfile
        image: server
        ports:
         - "80:80"
        volumes:
         - ${yvideojs}:/usr/local/apache2/htdocs/yvideojs
         - ${subtitle_timeline_editor}:/usr/local/apache2/htdocs/subtitle-timeline-editor
         - ${TimedText}:/usr/local/apache2/htdocs/TimedText
         - ${EditorWidgets}:/usr/local/apache2/htdocs/EditorWidgets

    database:
        volumes:
         - ${YVIDEO_SQL_DATA}:/var/lib/mysql

