version: '3.1'

services:
    ylex:
        depends_on:
            - database
        build:
            context: ../../docker_contexts/travis/ylex
            dockerfile: Dockerfile
        image: ylex_travis
        command: ["sbt", "-no-colors", "test"]

