version: '3.1'

services:
    yvideo:
        depends_on:
            - database
        build:
            context: ../../docker_contexts/travis/yvideo
            dockerfile: Dockerfile
        image: yvideo_travis
        command: ["sbt", "-no-colors", "test"]

